services:
  # Agent 1 - The Analyst
  agent-1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - .:/app
    network_mode: "host"
    restart: unless-stopped
    command: ["python", "agent1.py", "dev"]
    container_name: agent-1-analyst

  # Agent 2 - The Creative
  agent-2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - .:/app
    network_mode: "host"
    restart: unless-stopped
    command: ["python", "agent2.py", "dev"]
    container_name: agent-2-creative
